
-- =============================================
-- 01_SCHEMA_ORACLE_GS.sql
-- Tabelas com prefixo TB_GS_*
-- =============================================

-- DROPS (somente DEV)
BEGIN FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
  'TB_GS_AUDITORIA','TB_GS_EXPORT_LOG','TB_GS_CHAT_HIST','TB_GS_CERTIFICADO','TB_GS_BLOG_POST','TB_GS_EMPRESA','TB_GS_USUARIO'
)) LOOP EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE'; END LOOP; END;
/
BEGIN FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_TB_GS_%') LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||s.sequence_name;
END LOOP; END;
/

-- =====================
-- TABELAS (3FN)
-- =====================

CREATE TABLE TB_GS_USUARIO (
  ID_USUARIO   NUMBER(6)       CONSTRAINT PK_TB_GS_USUARIO PRIMARY KEY,
  NM_USUARIO   VARCHAR2(100)   CONSTRAINT NN_TB_GS_USUARIO_NM NOT NULL,
  DS_EMAIL     VARCHAR2(120)   CONSTRAINT NN_TB_GS_USUARIO_EMAIL NOT NULL,
  DS_PASSWORD  VARCHAR2(60)    CONSTRAINT NN_TB_GS_USUARIO_PWD NOT NULL,
  TP_ROLE      VARCHAR2(20)    DEFAULT 'USER' CONSTRAINT NN_TB_GS_USUARIO_ROLE NOT NULL,
  DT_CRIACAO   DATE            DEFAULT SYSDATE
);
ALTER TABLE TB_GS_USUARIO ADD CONSTRAINT UQ_TB_GS_USUARIO_EMAIL UNIQUE (DS_EMAIL);
ALTER TABLE TB_GS_USUARIO ADD CONSTRAINT CK_TB_GS_USUARIO_ROLE CHECK (TP_ROLE IN ('USER','ADMIN'));

CREATE TABLE TB_GS_BLOG_POST (
  ID_POST          NUMBER(6)      CONSTRAINT PK_TB_GS_BLOG_POST PRIMARY KEY,
  DS_TITULO        VARCHAR2(120)  CONSTRAINT NN_TB_GS_POST_TITULO NOT NULL,
  DS_DESCRICAO     VARCHAR2(600),
  DS_IMAGE_URL     VARCHAR2(300),
  DS_TAG           VARCHAR2(50),
  DT_CRIACAO       DATE           DEFAULT SYSDATE,
  ID_USUARIO_CRIADOR NUMBER(6)    CONSTRAINT FK_TB_GS_POST_USUARIO REFERENCES TB_GS_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_GS_EMPRESA (
  ID_EMPRESA   NUMBER(6)       CONSTRAINT PK_TB_GS_EMPRESA PRIMARY KEY,
  NM_EMPRESA   VARCHAR2(120)   CONSTRAINT NN_TB_GS_EMPRESA_NM NOT NULL,
  DS_EMPRESA   VARCHAR2(300),
  DS_AREA      VARCHAR2(60),
  FL_HIRING_NOW CHAR(1)        DEFAULT 'N' CONSTRAINT CK_TB_GS_EMPRESA_HIRING CHECK (FL_HIRING_NOW IN ('Y','N')),
  DS_LOGO_URL  VARCHAR2(300),
  DS_WEBSITE   VARCHAR2(150),
  DT_CRIACAO   DATE            DEFAULT SYSDATE
);

CREATE TABLE TB_GS_CHAT_HIST (
  ID_CHAT     NUMBER(6)        CONSTRAINT PK_TB_GS_CHAT_HIST PRIMARY KEY,
  ID_USUARIO  NUMBER(6)        CONSTRAINT FK_TB_GS_CHAT_USUARIO REFERENCES TB_GS_USUARIO(ID_USUARIO),
  DS_PROMPT   VARCHAR2(2000),
  DS_RESPONSE VARCHAR2(2000),
  DT_CRIACAO  DATE             DEFAULT SYSDATE
);

CREATE TABLE TB_GS_CERTIFICADO (
  ID_CERTIFICADO NUMBER(6)     CONSTRAINT PK_TB_GS_CERTIFICADO PRIMARY KEY,
  ID_USUARIO     NUMBER(6)     CONSTRAINT FK_TB_GS_CERT_USUARIO REFERENCES TB_GS_USUARIO(ID_USUARIO),
  DT_EMISSAO     DATE          DEFAULT SYSDATE,
  DS_TITULO      VARCHAR2(100) DEFAULT 'Remote Work Ready'
);

CREATE TABLE TB_GS_EXPORT_LOG (
  ID_EXPORT      NUMBER(10)    CONSTRAINT PK_TB_GS_EXPORT_LOG PRIMARY KEY,
  DT_GERACAO     DATE          DEFAULT SYSDATE,
  DS_DATASET_JSON CLOB
);

CREATE TABLE TB_GS_AUDITORIA (
  ID_AUDITORIA NUMBER(10)      CONSTRAINT PK_TB_GS_AUDITORIA PRIMARY KEY,
  NM_USUARIO   VARCHAR2(120),
  TP_OPERACAO  VARCHAR2(10),
  NM_TABELA    VARCHAR2(50),
  ID_REGISTRO  VARCHAR2(50),
  OLD_VALUES   CLOB,
  NEW_VALUES   CLOB,
  DT_OPERACAO  DATE DEFAULT SYSDATE
);

-- =====================
-- SEQUÊNCIAS (opcional com GS no nome)
-- =====================
CREATE SEQUENCE SEQ_TB_GS_USUARIO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_BLOG_POST    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_EMPRESA      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_CHAT_HIST    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_CERTIFICADO  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_AUDITORIA    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB_GS_EXPORT_LOG   START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================
-- ÍNDICES
-- =====================
CREATE INDEX IX_TB_GS_POST_USUARIO ON TB_GS_BLOG_POST(ID_USUARIO_CRIADOR);
CREATE INDEX IX_TB_GS_CHAT_USUARIO ON TB_GS_CHAT_HIST(ID_USUARIO);
CREATE INDEX IX_TB_GS_CERT_USUARIO ON TB_GS_CERTIFICADO(ID_USUARIO);
