
-- =============================================
-- 03_TRIGGERS_AUDIT_GS.sql
-- Formato: TRG_AUD_TB_GS_<tabela>
-- =============================================

CREATE OR REPLACE TRIGGER TRG_AUD_TB_GS_USUARIO
AFTER INSERT OR UPDATE OR DELETE ON TB_GS_USUARIO
FOR EACH ROW
DECLARE v_old CLOB; v_new CLOB; v_id VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    v_new := 'NM='||:NEW.NM_USUARIO||';EMAIL='||:NEW.DS_EMAIL||';ROLE='||:NEW.TP_ROLE;
    v_id := :NEW.ID_USUARIO;
    INSERT INTO TB_GS_AUDITORIA (ID_AUDITORIA,NM_USUARIO,TP_OPERACAO,NM_TABELA,ID_REGISTRO,OLD_VALUES,NEW_VALUES,DT_OPERACAO)
    VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'INSERT', 'TB_GS_USUARIO', v_id, NULL, v_new, SYSDATE);
  ELSIF UPDATING THEN
    v_old := 'NM='||:OLD.NM_USUARIO||';EMAIL='||:OLD.DS_EMAIL||';ROLE='||:OLD.TP_ROLE;
    v_new := 'NM='||:NEW.NM_USUARIO||';EMAIL='||:NEW.DS_EMAIL||';ROLE='||:NEW.TP_ROLE;
    v_id := :NEW.ID_USUARIO;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'UPDATE', 'TB_GS_USUARIO', v_id, v_old, v_new, SYSDATE);
  ELSIF DELETING THEN
    v_old := 'NM='||:OLD.NM_USUARIO||';EMAIL='||:OLD.DS_EMAIL||';ROLE='||:OLD.TP_ROLE;
    v_id := :OLD.ID_USUARIO;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'DELETE', 'TB_GS_USUARIO', v_id, v_old, NULL, SYSDATE);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_TB_GS_BLOG_POST
AFTER INSERT OR UPDATE OR DELETE ON TB_GS_BLOG_POST
FOR EACH ROW
DECLARE v_old CLOB; v_new CLOB; v_id VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    v_new := 'TIT='||:NEW.DS_TITULO||';USR='||:NEW.ID_USUARIO_CRIADOR;
    v_id := :NEW.ID_POST;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'INSERT', 'TB_GS_BLOG_POST', v_id, NULL, v_new, SYSDATE);
  ELSIF UPDATING THEN
    v_old := 'TIT='||:OLD.DS_TITULO||';USR='||:OLD.ID_USUARIO_CRIADOR;
    v_new := 'TIT='||:NEW.DS_TITULO||';USR='||:NEW.ID_USUARIO_CRIADOR;
    v_id := :NEW.ID_POST;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'UPDATE', 'TB_GS_BLOG_POST', v_id, v_old, v_new, SYSDATE);
  ELSIF DELETING THEN
    v_old := 'TIT='||:OLD.DS_TITULO||';USR='||:OLD.ID_USUARIO_CRIADOR;
    v_id := :OLD.ID_POST;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'DELETE', 'TB_GS_BLOG_POST', v_id, v_old, NULL, SYSDATE);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_TB_GS_EMPRESA
AFTER INSERT OR UPDATE OR DELETE ON TB_GS_EMPRESA
FOR EACH ROW
DECLARE v_old CLOB; v_new CLOB; v_id VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    v_new := 'NM='||:NEW.NM_EMPRESA||';H='||:NEW.FL_HIRING_NOW;
    v_id := :NEW.ID_EMPRESA;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'INSERT', 'TB_GS_EMPRESA', v_id, NULL, v_new, SYSDATE);
  ELSIF UPDATING THEN
    v_old := 'NM='||:OLD.NM_EMPRESA||';H='||:OLD.FL_HIRING_NOW;
    v_new := 'NM='||:NEW.NM_EMPRESA||';H='||:NEW.FL_HIRING_NOW;
    v_id := :NEW.ID_EMPRESA;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'UPDATE', 'TB_GS_EMPRESA', v_id, v_old, v_new, SYSDATE);
  ELSIF DELETING THEN
    v_old := 'NM='||:OLD.NM_EMPRESA||';H='||:OLD.FL_HIRING_NOW;
    v_id := :OLD.ID_EMPRESA;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'DELETE', 'TB_GS_EMPRESA', v_id, v_old, NULL, SYSDATE);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_TB_GS_CHAT_HIST
AFTER INSERT OR UPDATE OR DELETE ON TB_GS_CHAT_HIST
FOR EACH ROW
DECLARE v_old CLOB; v_new CLOB; v_id VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    v_new := 'USR='||:NEW.ID_USUARIO||';PROMPT_LEN='||LENGTH(:NEW.DS_PROMPT);
    v_id := :NEW.ID_CHAT;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'INSERT', 'TB_GS_CHAT_HIST', v_id, NULL, v_new, SYSDATE);
  ELSIF UPDATING THEN
    v_old := 'USR='||:OLD.ID_USUARIO||';PROMPT_LEN='||LENGTH(:OLD.DS_PROMPT);
    v_new := 'USR='||:NEW.ID_USUARIO||';PROMPT_LEN='||LENGTH(:NEW.DS_PROMPT);
    v_id := :NEW.ID_CHAT;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'UPDATE', 'TB_GS_CHAT_HIST', v_id, v_old, v_new, SYSDATE);
  ELSIF DELETING THEN
    v_old := 'USR='||:OLD.ID_USUARIO||';PROMPT_LEN='||LENGTH(:OLD.DS_PROMPT);
    v_id := :OLD.ID_CHAT;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'DELETE', 'TB_GS_CHAT_HIST', v_id, v_old, NULL, SYSDATE);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_TB_GS_CERTIFICADO
AFTER INSERT OR UPDATE OR DELETE ON TB_GS_CERTIFICADO
FOR EACH ROW
DECLARE v_old CLOB; v_new CLOB; v_id VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    v_new := 'USR='||:NEW.ID_USUARIO||';TIT='||:NEW.DS_TITULO;
    v_id := :NEW.ID_CERTIFICADO;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'INSERT', 'TB_GS_CERTIFICADO', v_id, NULL, v_new, SYSDATE);
  ELSIF UPDATING THEN
    v_old := 'USR='||:OLD.ID_USUARIO||';TIT='||:OLD.DS_TITULO;
    v_new := 'USR='||:NEW.ID_USUARIO||';TIT='||:NEW.DS_TITULO;
    v_id := :NEW.ID_CERTIFICADO;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'UPDATE', 'TB_GS_CERTIFICADO', v_id, v_old, v_new, SYSDATE);
  ELSIF DELETING THEN
    v_old := 'USR='||:OLD.ID_USUARIO||';TIT='||:OLD.DS_TITULO;
    v_id := :OLD.ID_CERTIFICADO;
    INSERT INTO TB_GS_AUDITORIA VALUES (SEQ_TB_GS_AUDITORIA.NEXTVAL, USER, 'DELETE', 'TB_GS_CERTIFICADO', v_id, v_old, NULL, SYSDATE);
  END IF;
END;
/
