
--------------------------------------------------------------------------------
-- CRIAÇÃO DAS TABELAS (3FN - Terceira Forma Normal)
--------------------------------------------------------------------------------
PROMPT Criando estrutura de tabelas...

-- 1. USUÁRIO (entidade principal)
CREATE TABLE TB_GS_USUARIO (
    ID_USUARIO     NUMBER(8)       NOT NULL,
    NM_USUARIO     VARCHAR2(100)   NOT NULL,
    DS_EMAIL       VARCHAR2(150)   NOT NULL,
    DS_PASSWORD    VARCHAR2(100)   NOT NULL,
    TP_PERFIL      VARCHAR2(50)    DEFAULT 'JUNIOR',
    TP_ROLE        VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    NR_EXPERIENCIA NUMBER(2)       DEFAULT 0,
    VL_AVALIACAO   NUMBER(3,2),
    DT_CRIACAO     DATE            DEFAULT SYSDATE,
    FL_ATIVO       CHAR(1)         DEFAULT 'Y' CHECK (FL_ATIVO IN ('Y','N')),
    
    CONSTRAINT PK_GS_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_GS_USUARIO_EMAIL UNIQUE (DS_EMAIL),
    CONSTRAINT CK_GS_USUARIO_ROLE CHECK (TP_ROLE IN ('USER','ADMIN')),
    CONSTRAINT CK_GS_USUARIO_PERFIL CHECK (TP_PERFIL IN ('JUNIOR','PLENO','SENIOR')),
    CONSTRAINT CK_GS_USUARIO_EXP CHECK (NR_EXPERIENCIA >= 0),
    CONSTRAINT CK_GS_USUARIO_AVAL CHECK (VL_AVALIACAO BETWEEN 1.0 AND 5.0)
);

CREATE SEQUENCE SEQ_TB_GS_USUARIO START WITH 1 INCREMENT BY 1 CACHE 20;

-- Índices para performance (com proteção contra duplicatas)
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_USUARIO_EMAIL ON TB_GS_USUARIO(DS_EMAIL)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_USUARIO_EMAIL criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_USUARIO_EMAIL já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- 2. EMPRESA (parceiras para vagas remotas)
CREATE TABLE TB_GS_EMPRESA (
    ID_EMPRESA     NUMBER(8)      NOT NULL,
    NM_EMPRESA     VARCHAR2(150)  NOT NULL,
    DS_AREA        VARCHAR2(100),
    FL_HIRING_NOW  CHAR(1)        DEFAULT 'N' CHECK (FL_HIRING_NOW IN ('Y','N')),
    DS_WEBSITE     VARCHAR2(200),
    DT_CRIACAO     DATE           DEFAULT SYSDATE,
    
    CONSTRAINT PK_GS_EMPRESA PRIMARY KEY (ID_EMPRESA)
);

CREATE SEQUENCE SEQ_TB_GS_EMPRESA START WITH 1 INCREMENT BY 1 CACHE 20;

-- 3. BLOG_POST (conteúdo educacional - só ADMIN cria)
CREATE TABLE TB_GS_BLOG_POST (
    ID_POST            NUMBER(8)       NOT NULL,
    DS_TITULO          VARCHAR2(200)   NOT NULL,
    DS_DESCRICAO       VARCHAR2(2000)  NOT NULL,
    DS_IMAGE_URL       VARCHAR2(400),
    DS_TAG             VARCHAR2(50),
    ID_USUARIO_CRIADOR NUMBER(8)       NOT NULL,
    QT_VISUALIZACOES   NUMBER(8)       DEFAULT 0,
    DT_CRIACAO         DATE            DEFAULT SYSDATE,
    
    CONSTRAINT PK_GS_POST PRIMARY KEY (ID_POST),
    CONSTRAINT FK_POST_USUARIO FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES TB_GS_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TB_GS_POST START WITH 1 INCREMENT BY 1 CACHE 20;

-- Índices para performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_POST_TAG ON TB_GS_BLOG_POST(DS_TAG)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_POST_TAG criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_POST_TAG já existe');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_POST_CRIADOR ON TB_GS_BLOG_POST(ID_USUARIO_CRIADOR)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_POST_CRIADOR criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_POST_CRIADOR já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- 4. CERTIFICADO (gamificação por engajamento)
CREATE TABLE TB_GS_CERTIFICADO (
    ID_CERTIFICADO NUMBER(8)      NOT NULL,
    ID_USUARIO     NUMBER(8)      NOT NULL,
    DS_TITULO      VARCHAR2(150)  NOT NULL,
    DS_DESCRICAO   VARCHAR2(500),
    DT_EMISSAO     DATE           DEFAULT SYSDATE,
    
    CONSTRAINT PK_GS_CERTIFICADO PRIMARY KEY (ID_CERTIFICADO),
    CONSTRAINT FK_CERT_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_GS_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TB_GS_CERTIFICADO START WITH 1 INCREMENT BY 1 CACHE 20;

-- Índices para performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_CERT_USUARIO ON TB_GS_CERTIFICADO(ID_USUARIO)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_CERT_USUARIO criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_CERT_USUARIO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- 5. POST_LEITURA (registro de leitura para certificados)
CREATE TABLE TB_GS_POST_LEITURA (
    ID_LEITURA     NUMBER(8)      NOT NULL,
    ID_USUARIO     NUMBER(8)      NOT NULL,
    ID_POST        NUMBER(8)      NOT NULL,
    DT_LEITURA     DATE           DEFAULT SYSDATE,
    QT_TEMPO_SEG   NUMBER(6),
    
    CONSTRAINT PK_GS_LEITURA PRIMARY KEY (ID_LEITURA),
    CONSTRAINT UK_GS_LEITURA_USER_POST UNIQUE (ID_USUARIO, ID_POST),
    CONSTRAINT FK_LEITURA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_GS_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_LEITURA_POST FOREIGN KEY (ID_POST)
        REFERENCES TB_GS_BLOG_POST(ID_POST) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TB_GS_LEITURA START WITH 1 INCREMENT BY 1 CACHE 20;

-- Índices para performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_LEITURA_USUARIO ON TB_GS_POST_LEITURA(ID_USUARIO)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_LEITURA_USUARIO criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_LEITURA_USUARIO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- 6. AUDITORIA (trigger automático para rastreamento)
CREATE TABLE TB_GS_AUDITORIA (
    ID_AUDITORIA   NUMBER(10)     NOT NULL,
    NM_TABELA      VARCHAR2(50)   NOT NULL,
    TP_OPERACAO    VARCHAR2(10)   NOT NULL,
    ID_REGISTRO    NUMBER(10),
    NM_USUARIO_DB  VARCHAR2(50),
    DS_DADOS_OLD   VARCHAR2(4000),
    DS_DADOS_NEW   VARCHAR2(4000),
    DT_OPERACAO    DATE           DEFAULT SYSDATE,
    
    CONSTRAINT PK_GS_AUDITORIA PRIMARY KEY (ID_AUDITORIA)
);

CREATE SEQUENCE SEQ_TB_GS_AUDITORIA START WITH 1 INCREMENT BY 1 CACHE 50;

-- Índices para performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_AUD_TABELA ON TB_GS_AUDITORIA(NM_TABELA)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_AUD_TABELA criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_AUD_TABELA já existe');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_AUD_DATA ON TB_GS_AUDITORIA(DT_OPERACAO)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_AUD_DATA criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_AUD_DATA já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- ========================================================================
-- TABELA 9: HISTÓRICO DE CONVERSAS DO CHAT
-- ========================================================================
BEGIN
    EXECUTE IMMEDIATE '
CREATE TABLE TB_GS_CHAT_HISTORY (
    ID_CHAT       NUMBER GENERATED BY DEFAULT AS IDENTITY
                  CONSTRAINT PK_TB_GS_CHAT_HISTORY PRIMARY KEY,

    ID_USUARIO    NUMBER(6)    NOT NULL
                  CONSTRAINT FK_TB_GS_CHAT_HISTORY_USUARIO
                  REFERENCES TB_GS_USUARIO(ID_USUARIO),

    PROMPT        CLOB         NOT NULL,
    RESPONSE      CLOB,

    DT_CRIACAO    DATE         DEFAULT SYSDATE NOT NULL
)';
    DBMS_OUTPUT.PUT_LINE('✓ Tabela TB_GS_CHAT_HISTORY criada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('• Tabela TB_GS_CHAT_HISTORY já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Índice para performance do histórico
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_CHAT_USUARIO ON TB_GS_CHAT_HISTORY(ID_USUARIO)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_CHAT_USUARIO criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_CHAT_USUARIO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GS_CHAT_DATA ON TB_GS_CHAT_HISTORY(DT_CRIACAO)';
    DBMS_OUTPUT.PUT_LINE('✓ Índice IDX_GS_CHAT_DATA criado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1408 THEN
            DBMS_OUTPUT.PUT_LINE('• Índice IDX_GS_CHAT_DATA já existe');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('✓ Tabela TB_GS_CHAT_HISTORY criada com sucesso!');
END;
/

-- 7. EXPORT_LOG (controle de exportações para MongoDB)
CREATE TABLE TB_GS_EXPORT_LOG (
    ID_EXPORT      NUMBER(8)      NOT NULL,
    DT_GERACAO     DATE           DEFAULT SYSDATE,
    TP_EXPORT      VARCHAR2(50)   DEFAULT 'FULL',
    QT_REGISTROS   NUMBER(8),
    DS_DATASET_JSON CLOB,
    FL_SUCESSO     CHAR(1)        DEFAULT 'N' CHECK (FL_SUCESSO IN ('Y','N')),
    DS_OBSERVACAO  VARCHAR2(500),
    
    CONSTRAINT PK_GS_EXPORT PRIMARY KEY (ID_EXPORT)
);

CREATE SEQUENCE SEQ_TB_GS_EXPORT START WITH 1 INCREMENT BY 1 CACHE 10;
